name: ci

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
      - name: Shorten commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: codetreelearners/python-app:${{ steps.vars.outputs.SHORT_SHA }}
    outputs:
      IMAGE_TAG: ${{ steps.vars.outputs.SHORT_SHA }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Modify values.yaml with new image tag
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.IMAGE_TAG }}
          sudo apt-get update && sudo apt-get install -y yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.IMAGE_TAG }}"' charts/python-app/values.yaml

      - name: Commit and push changes to values.yaml
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update values.yaml with image tag to ${{ needs.ci.outputs.IMAGE_TAG }}"

      - name: Install ArgoCD CLI
        run: |
          sudo curl -ksSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app